modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/thepwrtank18/UncraftingTableUpdate/issues" #optional

[[mods]] #mandatory
modId="uncrafting" #mandatory
version="1.15.2-1.0.0" #mandatory
displayName="Uncrafting Table" #mandatory
displayURL="https://github.com/thepwrtank18/UncraftingTableUpdate/" #optional
credits="jglrxavpok for making the textures, TurtyWurty for making a modding tutorial" #optional
authors="TheTank20" #optional
description='''
A version of the Uncrafting Table for Minecraft 1.15.2.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
